### ISSUE TITLE
No ArrayList implementation

### ISSUE THREAD

**Issue by igorastvorov** [quinntaylor/CHDataStructures#6]
Hello.
If anyone checks this out. I've noticed there's no ArrayList implementation in CHDataStructures. Maybe we should add one? Consider having a look at my implementation here - https://github.com/igorastvorov/CollectionsKit/blob/master/CollectionsKit/CKArrayList.h

**Comment by quinntaylor** [comment]
An array list is the same thing as a dynamic array, and we already get that from NSMutableArray. In fact, your implementation just wraps one and exposes different API. This would be counterintuitive to Cocoa developers, and be slower with no additional benefits. CHDS already has stack and queue structures that serve similar purposes. I don't think it makes sense to add this. Thanks for the suggestion, though!

**Comment by igorastvorov** [comment]
Okay, agree on that. Thanks for the reply.
