### ISSUE TITLE
CHDataStructures/source/Util.m:46:49: Too many arguments to function call, expected 0, have 2

### ISSUE THREAD

**Issue by fatuhoku** [quinntaylor/CHDataStructures#7]
When included as a Cocoapod, using Xcode 6 GM, I get this:

![screen shot 2015-01-21 at 22 26 55](https://cloud.githubusercontent.com/assets/430233/5846583/a48892ce-a1bc-11e4-80fe-0279af587b04.png)

I think it's an incarnation of this issue: http://stackoverflow.com/q/25852079/590767

**Comment by quinntaylor** [comment]
I plan to rip out GC support entirely, which will get rid of this issue.

**Comment by quinntaylor** [comment]
Removed in 32b3659d4f801740b4acfceb281f2c857b77cbba.

**Comment by fatuhoku** [comment]
:+1: :beers:

**Comment by fatuhoku** [comment]
Ooh, it would be good to bump the Cocoapods version — I'm having to declare it like this at the moment:

```ruby
pod 'CHDataStructures', :git => 'https://github.com/quinntaylor/CHDataStructures', :commit => '12cd020da5bcf57ee05a85d04e512535e89e4fcf'
```

**Comment by fatuhoku** [comment]
BUMP podspec needs updating!

**Comment by andygeers** [comment]
+1 a year later it seems the podspec still needs updating
